### PR TITLE
add Travis-CI testing

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
see https://travis-ci.org/MartinNowak/d-leveldb/builds/49031774

**Comment by MartinNowak** [comment]
Library seems to work well, maybe you can ask the http://leveldb.org/ people to link to your D implementation.

**Comment by bheads** [comment]
Thanks! I need to stay on top of github better

**Comment by MartinNowak** [comment]
No problem, I'm glad you still maintain this.

**Pull request merged**
